### ISSUE TITLE
won't work

### ISSUE THREAD

**Issue by cainiaokun** [lucasan123/Autobuy-pancake-bot#1]
https://bscscan.com/tx/0x33349a26c638706bd691b1073460f1955a76ef1df75db584193534dda3793c28

Fail with error 'TransferHelper: TRANSFER_FROM_FAILED'

help me fix that, so so thanks

**Comment by lucasan123** [comment]
You have to approve wbnb for spending

**Comment by lucasan123** [comment]
fixed the source code with automatic wbnb approve
